### PR TITLE
Update exporters build instructions.

### PR DESCRIPTION
**Pull request by AlekSi**

### CODE REVIEW

**Comment by EvgeniyPatlan** [comment]
If you close my PR than please also set correct version

**Comment by AlekSi** [comment]
1.2.0 is PMM version, not exporter versions. And they are specified in VERSION files in repos, and in git tags.

**Comment by EvgeniyPatlan** [comment]
@AlekSi you have closed my commit. So there was additional change for version change. If it is supposed that your commit should take care about changes I've suggested than please set version.

**Comment by AlekSi** [comment]
Ah, sorry, missed that. #57.

**Pull request merged**
