### PR TITLE
add option to disable Query examples

### PR DESCRIPTION
**Pull request by delgod**

### CODE REVIEW

**Comment by rnovikovP** [comment]
are  we going to store everything  from vendor inside repo ??

**Comment by AlekSi** [comment]
Yep, that's the Go way. For example, see https://github.com/github/gitignore/pull/2266.

**Comment by delgod** [comment]
@rnovikovP it is common practice
see
https://github.com/grafana/grafana/tree/master/vendor
https://github.com/prometheus/prometheus/tree/master/vendor
https://github.com/hashicorp/consul/tree/master/vendor
https://github.com/github/orchestrator/tree/master/vendor

**Comment by delgod** [comment]
@arvenil I fixed travis config

**Comment by arvenil** [comment]
Why we want to have `vendor` dir in project?

I'm not a big fun of additional 120000 lines of data and noise in repo, but the biggest concern I have is that nobody is going to verify if those 120000 lines of code are actually valid, not changed by developer. With commit hashes we were sure they are unmodified external sources. I often change something in `vendor` libs, e.g. if I try to debug or fix external library, and I'm afraid we might end up one day with some changes done by developers in `vendor` (intentional or unintentional) and we will have really happy debuging times that will end up with `diff -Nru vendor/lib external/lib`.

Also, just to be sure, you are aware with `vendor` dir this repository never should be used by other go packages as import. https://github.com/Masterminds/glide#q-should-i-check-vendor-into-version-control
> Q: Should I check vendor/ into version control?
> 
> That's up to you. It's not necessary, but it may also cause you extra work and lots of extra space in your VCS. There may also be unforeseen errors.
> e.g. https://github.com/mattfarina/golang-broken-vendor

Of course I understand this way we will have backup of all external libraries - I'm only not sure if it's worth the hassle.

In any case 👍  from me whatever your choice will be ;)

**Comment by AlekSi** [comment]
> I'm not a big fun of additional 120000 lines of data and noise in repo

Dependencies are not a noise if you are using them, and you do use them.

> he biggest concern I have is that nobody is going to verify if those 120000 lines of code are actually valid, not changed by developer. With commit hashes we were sure they are unmodified external sources. […] Maybe there is a way to verify that with vendor dir?

A proper vendoring tool can tell you that code in `vendor/` differs from that commit/tag upstream. It also works the other way around: once I noticed that upstream tagged one commit, and then re-used tag for another commit.

> Also with vendor dir this repository never should be used by other go packages as import.

And that's a _real_ PITA for Go libraries authors. If you do vendor your dependencies, a user of your library will have a bad time. If you do not vendor, then you will have a bad time when (_when_, not _if_) upstream will break API without changing import path.
But pmm-client is not a library, it's a program, so that's not a problem.

**Comment by arvenil** [comment]
> A proper vendoring tool can tell you that code in vendor/ differs from that commit/tag upstream.

True. Do we have that tool now? Can we add this verification to build process on travis? I see `govendor` has hashes in config file so maybe indeed we could do that.

> It also works the other way around: once I noticed that upstream tagged one commit, and then re-used tag for another commit.

Tags - yes, that's how they work, but I understand we address deps by hash https://github.com/percona/pmm-client/blob/master/vendor/vendor.json#L226

**Comment by delgod** [comment]
Hi @percona-csalguero, @rnovikovP 

I think problem with the Percona Toolkit is very good example why we should add vendor directory.
root of the issue is simple - vendor directory is different on developer machine and on jenkins node.
so it means that build results each time different (in different time and in different environments).
As result we have frozen release process, because we cannot even build and test new code, but we have very-strict deadline, due to this situation some people very stressed.

Again, "Reproducible builds" it is very important thing in Release and DevOps process, please lets start use this approach.

I added decencies test (for issues like in Mongo Exporter), please review it https://github.com/percona/pmm-client/pull/24/commits/1514e4267117b3ebf8ad393fdc0e9ebe3f1b1d13
this change give us possibility to be sure that our vendor dir is not broken during every pull request on github, after this change we have both wins, vendor dir verification and "Reproducible builds" simultaneously.

**Comment by arvenil** [comment]
> I think problem with the Percona Toolkit is very good example why we should add vendor directory.
root of the issue is simple - vendor directory is different on developer machine and on jenkins node.

There is no travis build for percona-toolkit :) To me this is the biggest problem.

> I added decencies test

That looks good, this addresses my biggest concerns 👍

**Comment by percona-csalguero** [comment]
The problem building percona Toolkit was an error in the environment set up.
The repo was cloned into the `${GOPATH}` directory resulting in a `${GOPATH}/percona-toolkit` instead of being cloned into the `$GOPATH}/src/github.com/percona`.
For that reason, govendor/glide/go get were failing.
After putting everything in the correct place and setting the proper env vars, Evgeniy was able to build just using the make file that is pulling dependencies with `glide update`
Also, glide is getting dependencies using semantic versioning when possible or commit ids when sm is not available, so the builds are reproducible.
Maybe there is something else I am not understanding. 
Should we schedule some time to talk about this?
I am open to talk when you have a moment.

Thanks for helping us with this issue.

**Pull request closed without merging**
