### PR TITLE
Enable MyRocks metrics by default.

### PR DESCRIPTION
**Pull request by AlekSi**
PMM-1290.

### CODE REVIEW

**Comment by arvenil** [comment]
@AlekSi If we plan to enable it by default, can't we skip adding this additional flag in favor of leaving this to https://github.com/percona/pmm-client/pull/66 ?

**Comment by AlekSi** [comment]
We discussed it in #pmm-dev.

**Comment by arvenil** [comment]
I still believe proper solution should be detecting myrocks in exporter, and enable scrapper only when myrocks. We already have version checks and depending on version we disable or enable some features: https://github.com/percona/mysqld_exporter/blob/d7b7e87a8abd9dec10f7ea9d2cc518d3824f4b0e/mysqld_exporter.go#L469

Otherwise if there will be performance problems everyone will enable this flag, and if not then why use this flag at all. All in all you can always use https://github.com/percona/pmm-client/pull/66 instead.

**Comment by AlekSi** [comment]
Desided to implement MyRocks autodetection in mysqld_exporter instead.

**Pull request closed without merging**
