### PR TITLE
PMM-2003 Don't show headers if there are no external services

### PR DESCRIPTION
**Pull request by BupycHuk**
Delete all info related to external exporters on pmm-admin list output if there are no external services

### CODE REVIEW

**Comment by AlekSi** [comment]
```
{{if .ExternalServices}}
{{.ExternalTable}}{{end}}
```

That method should be called only if there are external services. So it is better to find out why this does not work instead of adding a hack.

**Comment by BupycHuk** [comment]
@AlekSi it's because when we remove external service it deletes only targets and keeps external service. I'm going to fix it

**Comment by rnovikovP** [comment]
@AlekSi @BupycHuk   let's merge this for 1.16.0

**Comment by rnovikovP** [comment]
@AlekSi  ^^ pls review

**Pull request merged**
