### PR TITLE
PMM-3421 modified node_exporter flags

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Comment by AlekSi** [comment]
I'm not sure why we need that change at all. We will not update node_exporter in PMM 1.x, and we will not have _that_ pmm-admin in 2.x.

**Comment by adivinho** [comment]
> I'm not sure why we need that change at all. We will not update node_exporter in PMM 1.x, and we will not have _that_ pmm-admin in 2.x.

It's required to be able to test a FB right now.
Also it would remind to not forget the flag in 2.x.

**Comment by AlekSi** [comment]
> It's required to be able to test a FB right now.

We don't test 2.0 changes with 1.x tools.

**Comment by rnovikovP** [comment]
will be reimplemented in pmm-agent

**Pull request closed without merging**
